# action.yml
name: 'License Check'
description: 'GitHub action to lint your python code with bandit'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  path:
    description: 'File or directory to run license check on'
    required: false
    default: '.'
outputs:
  output:
    description: 'The output of license check'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.disable }}
